using System.Text.Json;
using System.Text.Json.Serialization;

namespace PermaLocke.Data;

/// <summary>
/// The picture of each zone, from <c>Data/fotos.json</c>.
/// </summary>
/// <remarks>
/// Generated by <c>Probe --fotos</c>, which refuses to write the file unless every zone on the map
/// has a picture and every picture has a zone. That refusal is the whole safeguard: a mismatch
/// would show Ruta 4 on Ruta 5 and look perfectly correct.
/// </remarks>
public sealed class JsonZonePhotos(IReadOnlyDictionary<string, string> photos)
{
    public static JsonZonePhotos Empty { get; } = new(new Dictionary<string, string>());

    public int Count => photos.Count;

    public static JsonZonePhotos Load(string path)
    {
        if (!File.Exists(path))
        {
            return Empty;
        }

        try
        {
            using var stream = File.OpenRead(path);
            var file = JsonSerializer.Deserialize<PhotoFile>(stream);

            return file?.Photos is { Count: > 0 } entries
                ? new JsonZonePhotos(entries.Where(pair => !string.IsNullOrWhiteSpace(pair.Value))
                    .ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.Ordinal))
                : Empty;
        }
        catch (JsonException)
        {
            return Empty;
        }
    }

    /// <summary>The path relative to the application folder, or null when there is none.</summary>
    public string? For(string zoneId) => photos.GetValueOrDefault(zoneId);

    private sealed record PhotoFile(
        [property: JsonPropertyName("fotos")] IReadOnlyDictionary<string, string>? Photos);
}
