using System.Text.Json;
using System.Text.Json.Serialization;

namespace PermaLocke.Data;

/// <param name="Island">Which of the four islands, or null for a name nobody placed.</param>
public sealed record MapZone(string Name, string Island);

/// <summary>
/// Reads Data/islas.json: which island each of Alola's zones belongs to.
/// </summary>
/// <remarks>
/// <para>
/// The grouping is <b>measured, not remembered</b>. Zone data gives every zone a
/// <c>WorldIndex</c>, and although a "world" is a map rather than an island — there are 303 of
/// them — the four <em>outdoor</em> worlds turn out to be exactly the four islands, each carrying
/// its own run of routes: world 0 has Rutas 1-3, world 58 has 4-9, world 117 has 10-17 and world
/// 197 has Poni's. The interiors are numbered in between, so a zone's world index places it.
/// </para>
/// <para>
/// Checked against 21 names that can only belong to one island — Hauoli, Konikoni, Lanakila and so
/// on — with <b>zero contradictions</b>, which is what makes this an anchor rather than a guess. It
/// is worth having: from memory, Playa Big Wave and Colina Saltagua were both placed on the wrong
/// island before the measurement corrected them.
/// </para>
/// <para>
/// It is generated by <c>RomTool mundos</c> from the player's own cartridge, so it ships as a small
/// text file rather than as anything of Nintendo's.
/// </para>
/// </remarks>
public sealed class JsonIslandMap(IReadOnlyList<MapZone> zones)
{
    /// <summary>The islands in the order the game visits them, which is the order to draw them.</summary>
    public static readonly string[] Order = ["Melemele", "Akala", "Ula-Ula", "Poni"];

    public IReadOnlyList<MapZone> Zones { get; } = zones;

    /// <summary>Empty when the file is missing, so the map says so instead of inventing Alola.</summary>
    public static JsonIslandMap Empty { get; } = new([]);

    public static JsonIslandMap Load(string path)
    {
        if (!File.Exists(path))
        {
            return Empty;
        }

        using var stream = File.OpenRead(path);
        var file = JsonSerializer.Deserialize<IslandFile>(stream);

        if (file?.Islands is not { Count: > 0 } islands)
        {
            return Empty;
        }

        var zones = islands
            .SelectMany(pair => (pair.Value ?? [])
                .Where(name => !string.IsNullOrWhiteSpace(name))
                .Select(name => new MapZone(name.Trim(), pair.Key)))
            .OrderBy(zone => Array.IndexOf(Order, zone.Island))
            .ThenBy(zone => zone.Name, StringComparer.Ordinal)
            .ToArray();

        return new JsonIslandMap(zones);
    }

    /// <summary>The zones of one island, in name order.</summary>
    public IReadOnlyList<MapZone> Of(string island) =>
        [.. Zones.Where(zone => zone.Island == island)];

    private sealed record IslandFile(
        [property: JsonPropertyName("islands")] IReadOnlyDictionary<string, string[]?>? Islands);
}
