using System.Text.Json;
using System.Text.Json.Serialization;

namespace PermaLocke.Rules;

/// <param name="Names">Location names the area covers. More than one means it is ambiguous.</param>
public sealed record ZoneArea(
    [property: JsonPropertyName("area")] int Area,
    [property: JsonPropertyName("names")] IReadOnlyList<string> Names,
    [property: JsonPropertyName("hasEncounters")] bool HasEncounters);

/// <summary>
/// Translates the area the game reports into the zone the run records.
/// </summary>
/// <remarks>
/// <para>
/// Two numbering systems meet here. The game keeps the index of the encounter area (§23), while
/// the run identifies a zone by the normalised name of its location, because that is what a
/// captured Pokémon carries. The bridge is the name, and the table comes from the cartridge —
/// generated by <c>PermaLocke.RomTool zones</c>, never written by hand.
/// </para>
/// <para>
/// Most areas cover a single location, but not all: 8 of the 74 areas that have encounters
/// cover two, such as area 0, which is Route 1 and the Melemele Sea at once. For those the
/// table refuses to answer instead of picking one. Taking the player's Poké Balls away for a
/// zone they are not in would be worse than not enforcing the rule at all.
/// </para>
/// </remarks>
public sealed class ZoneTable
{
    private readonly Dictionary<int, ZoneArea> _areas;

    public ZoneTable(IEnumerable<ZoneArea> areas)
    {
        _areas = areas.ToDictionary(area => area.Area);
    }

    /// <summary>Areas known, whether or not they have encounters.</summary>
    public int Count => _areas.Count;

    /// <summary>Empty table: every lookup refuses. What is used when the file is missing.</summary>
    public static ZoneTable Empty { get; } = new([]);

    public static ZoneTable Load(string path)
    {
        if (!File.Exists(path))
        {
            return Empty;
        }

        using var stream = File.OpenRead(path);
        var document = JsonSerializer.Deserialize<ZoneTableFile>(stream);

        return document?.Areas is { Count: > 0 } areas ? new ZoneTable(areas) : Empty;
    }

    /// <summary>
    /// The single location this area covers, or null when the area is unknown or covers more
    /// than one. Callers must treat null as "do not act".
    /// </summary>
    public string? LocationNameFor(int area) =>
        _areas.TryGetValue(area, out var found) && found.Names.Count == 1 ? found.Names[0] : null;

    /// <summary>Whether the area is one the game can produce a wild encounter in.</summary>
    public bool HasEncounters(int area) =>
        _areas.TryGetValue(area, out var found) && found.HasEncounters;

    /// <summary>True when the area exists but covers several locations at once.</summary>
    public bool IsAmbiguous(int area) =>
        _areas.TryGetValue(area, out var found) && found.Names.Count > 1;

    private sealed record ZoneTableFile(
        [property: JsonPropertyName("areas")] IReadOnlyList<ZoneArea> Areas);
}
